api_keys:
  VirusTotal: "YOUR_VIRUSTOTAL_API_KEY"
  AbuseIPDB: "YOUR_ABUSEIPDB_API_KEY"
  Shodan: "YOUR_SHODAN_API_KEY"
  SecurityTrails: "YOUR_SECURITYTRAILS_API_KEY"
  IPQualityScore: "YOUR_IPQUALITYSCORE_API_KEY"

scan_settings:
  default_timeout: 5.0
  max_concurrent_scans: 1000  
  enable_quantum_resistant: true
  enable_advanced_analysis: true
  cache_duration: 7200

performance:
  max_threads: 8
  max_memory_mb: 1024
  enable_compression: true

security:
  min_encryption_strength: "VERY_STRONG"
  allow_weak_ciphers: false
  verify_certificates: true

advanced_security:
  quantum_resistant:
    enabled: true
    preferred_algorithm: "CRYSTALS-Kyber"
    key_size: 1024
  
  zero_trust:
    enabled: true
    jwt_validation: true
    mfa_required: true

monitoring:
  metrics_enabled: true
  prometheus_port: 9090
  grafana_enabled: true
  log_retention_days: 30
  alert_threshold: 0.8

optimization:
  async_dns_resolution: true
  connection_pooling: true
  max_concurrent_connections: 2000
  timeout_ms: 3000
  retry_strategy:
    max_attempts: 3
    backoff_factor: 1.5

cache:
  backend: "redis"
  ttl_seconds: 3600
  compression: true
  max_size_mb: 512
